namespace TLVParserApp
{
    public static class EMVFieldNames
    {
        public static Dictionary<string, string> emvTagNames = new Dictionary<string, string>
    {
        {"9F01", "Acquirer Identifier"},
    {"9F40", "Additional Terminal Capabilities"},
    {"81", "Amount, Authorised (Binary)"},
    {"9F02", "Amount, Authorised (Numeric)"},
    {"9F04", "Amount, Other (Binary)"},
    {"9F03", "Amount, Other (Numeric)"},
    {"9F3A", "Amount, Reference Currency"},
    {"9F26", "Application Cryptogram"},
    {"9F42", "Application Currency Code"},
    {"9F44", "Application Currency Exponent"},
    {"9F05", "Application Discretionary Data"},
    {"5F25", "Application Effective Date"},
    {"5F20", "Cardholder Name"},
    {"5F24", "Application Expiration Date"},
    {"94", "Application File Locator (AFL)"},
    {"4F", "Application Identifier (AID) – card"},
    {"9F06", "Application Identifier (AID) – terminal"},
    {"82", "Application Interchange Profile"},
    {"50", "Application Label"},
    {"9F12", "Application Preferred Name"},
    {"5A", "Application Primary Account Number (PAN)"},
    {"5F34", "Application Primary Account Number (PAN) Sequence Number"},
    {"87", "Application Priority Indicator"},
    {"9F3B", "Application Reference Currency"},
    {"9F43", "Application Reference Currency Exponent"},
    {"61", "Application Template"},
    {"9F36", "Application Transaction Counter (ATC)"},
    {"9F07", "Application Usage Control"},
    {"9F08", "Application Version Number"},
    {"9F09", "Application Version Number"},
    {"89", "Authorisation Code"},
    {"8A", "Authorisation Response Code"},
    {"5F54", "Bank Identifier Code (BIC)"},
    {"8C", "Card Risk Management Data Object List 1 (CDOL1)"},
    {"8D", "Card Risk Management Data Object List 2 (CDOL2)"},
    {"9F0B", "Cardholder Name Extended"},
    {"8E", "Cardholder Verification Method (CVM) List"},
    {"9F34", "Cardholder Verification Method (CVM) Results"},
    {"8F", "Certification Authority Public Key Index"},
    {"9F22", "Certification Authority Public Key Index"},
    {"83", "Command Template"},
    {"9F27", "Cryptogram Information Data"},
    {"9F45", "Data Authentication Code"},
    {"84", "Dedicated File (DF) Name"},
    {"9D", "Directory Definition File (DDF) Name"},
    {"73", "Directory Discretionary Template"},
    {"9F49", "Dynamic Data Authentication Data Object List (DDOL)"},
    {"70", "EMV Proprietary Template"},
    {"BF0C", "File Control Information (FCI) Issuer Discretionary Data"},
    {"A5", "File Control Information (FCI) Proprietary Template"},
    {"6F", "File Control Information (FCI) Template"},
    {"9F4C", "ICC Dynamic Number"},
    {"9F2D", "Integrated Circuit Card (ICC) PIN Encipherment Public Key Certificate"},
    {"9F2E", "Integrated Circuit Card (ICC) PIN Encipherment Public Key Exponent"},
    {"9F2F", "Integrated Circuit Card (ICC) PIN Encipherment Public Key Remainder"},
    {"9F46", "Integrated Circuit Card (ICC) Public Key Certificate"},
    {"9F47", "Integrated Circuit Card (ICC) Public Key Exponent"},
    {"9F48", "Integrated Circuit Card (ICC) Public Key Remainder"},
    {"9F1E", "Interface Device (IFD) Serial Number"},
    {"5F53", "International Bank Account Number (IBAN)"},
    {"9F0D", "Issuer Action Code – Default"},
    {"9F0E", "Issuer Action Code – Denial"},
    {"9F0F", "Issuer Action Code – Online"},
    {"9F10", "Issuer Application Data"},
    {"91", "Issuer Authentication Data"},
    {"9F11", "Issuer Code Table Index"},
    {"5F28", "Issuer Country Code"},
    {"5F55", "Issuer Country Code (alpha2 format)"},
    {"5F56", "Issuer Country Code (alpha3 format)"},
    {"42", "Issuer Identification Number (IIN)"},
    {"90", "Issuer Public Key Certificate"},
    {"92", "Issuer Public Key Remainder"},
    {"86", "Issuer Script Command"},
    {"9F18", "Issuer Script Identifier"},
    {"71", "Issuer Script Template 1"},
    {"72", "Issuer Script Template 2"},
    {"5F50", "Issuer URL"},
    {"9F13", "Last Online Application Transaction Counter (ATC) Register"},
    {"9F4D", "Log Entry"},
    {"9F4F", "Log Format"},
    {"9F14", "Lower Consecutive Offline Limit"},
    {"9F15", "Merchant Category Code"},
    {"9F16", "Merchant Identifier"},
    {"9F4E", "Merchant Name and Location"},
    {"9F17", "Personal Identification Number (PIN) Try Counter"},
    {"9F39", "Point-of-Service (POS) Entry Mode"},
    {"9F38", "Processing Options Data Object List (PDOL)"},
    {"80", "Response Message Template Format 1"},
    {"77", "Response Message Template Format 2"},
    {"5F30", "Service Code"},
    {"88", "Short File Identifier (SFI)"},
    {"9F4B", "Signed Dynamic Application Data"},
    {"93", "Signed Static Application Data"},
    {"9F4A", "Static Data Authentication Tag List"},
    {"9F33", "Terminal Capabilities"},
    {"9F1A", "Terminal Country Code"},
    {"9F1B", "Terminal Floor Limit"},
    {"9F1C", "Terminal Identification"},
    {"9F1D", "Terminal Risk Management Data"},
    {"9F35", "Terminal Type"},
    {"95", "Terminal Verification Results"},
    {"9F1F", "Track 1 Discretionary Data"},
    {"9F20", "Track 2 Discretionary Data"},
    {"57", "Track 2 Equivalent Data"},
    {"98", "Transaction Certificate (TC) Hash Value"},
    {"97", "Transaction Certificate Data Object List (TDOL)"},
    {"5F2A", "Transaction Currency Code"},
    {"5F36", "Transaction Currency Exponent"},
    {"9A", "Transaction Date"},
    {"99", "Transaction Personal Identification Number (PIN) Data"},
    {"9F3C", "Transaction Reference Currency Code"},
    {"9F3D", "Transaction Reference Currency Exponent"},
    {"9F41", "Transaction Sequence Counter"},
    {"9B", "Transaction Status Information"},
    {"9F21", "Transaction Time"},
    {"9C", "Transaction Type"},
    {"9F37", "Unpredictable Number"},
    {"9F23", "Upper Consecutive Offline Limit"},
    {"5F2D", "Language Preference"},
    {"9F32", "Issuer Public Key Exponent"},
    {"9F84", "NA"},
    {"9F86", "NA"},
    {"9F88", "NA"},
    {"9F8A", "NA"},
    {"9F85", "NA"},
    {"9F87", "NA"},
    {"9F89", "NA"},
    {"9F8B", "NA"},
    {"DF20", "Transaction Profile Objects 0 [DISCOVER] OR Counter 2 Number [MASTERCARD] OR Transaction Profile Objects 0 [TROY] OR Contactless Capabilities in BF63 [VISA]"},
    {"C3", "Currency Conversion Code 1 [DISCOVER] OR Card Issuer Action Code (Contact) - Decline [MASTERCARD] OR Currency Conversion Code 1 [TROY]"},
    {"C4", "Currency Conversion Code 2 [DISCOVER] OR Card Issuer Action Code (Contact) - Default [MASTERCARD] OR Currency Conversion Code 2 [TROY]"},
    {"C5", "Card Action Code (Contact) - Denial [DISCOVER] OR Card Issuer Action Code (Contact) - Online [MASTERCARD] OR Card Action Code (Contact) - Denial [TROY]"},
    {"C7", "Card Action Code (Contact) - Online [DISCOVER] OR CDOL 1 Related Data Length [MASTERCARD] OR Card Action Code (Contact) - Online [TROY]"},
    {"C8", "Lower Cumulative Offline Amount (LCOA)  [DISCOVER] OR CRM Country Code [MASTERCARD] OR Lower Cumulative Offline Amount (LCOA)  [TROY]"},
    {"C9", "Upper Cumulative Offline Amount (UCOA) [DISCOVER] OR Accumulator 1 Currency Code [MASTERCARD] OR Upper Cumulative Offline Amount (UCOA) [TROY]"},
    {"CA", "Single Transaction Amount (STA) Limit [DISCOVER] OR Accumulator 1 Lower Limit [MASTERCARD] OR Single Transaction Amount (STA) Limit [TROY]"},
    {"CB", "Lower Consecutive Offline Limit (LCOL) [DISCOVER] OR Accumulator 1 Upper Limit [MASTERCARD] OR Lower Consecutive Offline Limit (LCOL) [TROY]"},
    {"D1", "Offline Balance [DISCOVER] OR Accumulator 1 Currency Conversion Table [MASTERCARD] OR Offline Balance [TROY]"},
    {"D3", "CRM Currency Code [DISCOVER] OR Additional Check Table [MASTERCARD] OR CRM Currency Code [TROY]"},
    {"D5", "CVM-Cum Limit 1 [DISCOVER] OR Application Control (Contact) [MASTERCARD] OR CVM-Cum Limit 1 [TROY]"},
    {"D6", "CVM-Cum Limit 2 [DISCOVER] OR Default ARPC Response Code [MASTERCARD] OR CVM-Cum Limit 2 [TROY]"},
    {"9F7E", "DCVV [DISCOVER] OR Application Life Cycle Data [MASTERCARD] OR DCVV [TROY]"},
    {"56", "Track 1 Data [DISCOVER] OR Track 1 Data [MASTERCARD] OR Track 1 Data [TROY]"},
    {"9F62", "PCVC3 Track1 - Track 1 Bit Map for CVC3 [MASTERCARD]"},
    {"9F63", "PUNATC Track1 - Track 1 Bit Map for UN and ATC [MASTERCARD] OR Offline Counter Initial Value [VISA]"},
    {"9F64", "NATC Track1 - Track 1 Nr of ATC Digits [MASTERCARD]"},
    {"9F65", "PCVC3 Track2 - Track 2 Bit Map for CVC3 [MASTERCARD]"},
    {"9F66", "Terminal Transaction Qualifiers (TTQ) OR PUNATC Track2 - Track 2 Bit Map for UN and ATC [MASTERCARD]"},
    {"9F67", "NATC Track2 - Track 2 Nr of ATC Digits [MASTERCARD]"},
    {"9F6B", "Track 2 Data [MASTERCARD] OR Card CVM Limit [VISA]"},
    {"D7", "CVM-STA Limit 1 [DISCOVER] OR Application Control (Contactless) [MASTERCARD] OR CVM-STA Limit 1 [TROY]"},
    {"D8", "CVM-STA Limit 2 [DISCOVER] OR Application Interchange Profile (Contactless) [MASTERCARD] OR CVM-STA Limit 2 [TROY]"},
    {"D9", "CVM-Counter [DISCOVER] OR Application File Locator (Contactless) [MASTERCARD] OR CVM-Counter [TROY]"},
    {"DA", "CVM-Cons Limit 1 [DISCOVER] OR CVM-Cons Limit 1 [TROY]"},
    {"DB", "CVM-Cons Limit 2 [DISCOVER] OR CVM-Cons Limit 2 [TROY]"},
    {"DC", "IVCVC3(Track1) (Contactless) [MASTERCARD]"},
    {"DD", "IVCVC3(Track2) (Contactless) [MASTERCARD]"},
    {"9F8C", "NA"},
    {"9F6C", "Card Transaction Qualifiers (CTQ) OR Mag Stripe Application Version Number [MASTERCARD]"},
    {"9F83", "NA"},
    {"9F69", "Card Authentication Related Data"},
    {"9F8D", "NA"},
    {"DF11", "PDOL Check Table - Profile [DISCOVER] OR Accumulator 1 Control (Contact) [MASTERCARD] OR PDOL Check Table - Profile [TROY] OR Contactless Transaction Counter in BF55 (CLTC) [VISA] OR Consecutive Transaction Counter in BF56 (CTC) [VISA] OR Consecutive Transaction Counter International in BF57 (CTCI) [VISA] OR Cumulative Total Transaction Amount (CTTA) in BF58 [VISA]"},
    {"DF12", "PDOL Check Table - Online [DISCOVER] OR Accumulator 1 Control (Contactless) [MASTERCARD] OR PDOL Check Table - Online [TROY]"},
    {"DF14", "Accumulator 2 Control (Contact) [MASTERCARD]"},
    {"DF15", "Accumulator 2 Control (Contactless) [MASTERCARD]"},
    {"DF16", "Accumulator 2 Currency Code [MASTERCARD]"},
    {"DF17", "Accumulator 2 Currency Conversion Table [MASTERCARD]"},
    {"DF18", "Accumulator 2 Lower Limit [MASTERCARD]"},
    {"DF19", "Accumulator 2 Upper Limit [MASTERCARD]"},
    {"DF55", "NA"},
    {"9F8E", "NA"},
    {"DF4F", "NA"},
    {"DF5A", "NA"},
    {"DF5B", "NA"},
    {"DF59", "NA"},
    {"DF5C", "NA"},
    {"DF5E", "NA"},
    {"DF45", "NA"},
    {"DF5D", "NA"},
    {"DF46", "NA"},
    {"DF1A", "Counter 1 Control (Contact) [MASTERCARD]"},
    {"DF1B", "Counter 1 Control (Contactless) [MASTERCARD]"},
    {"DF1D", "Counter 2 Control (Contact) [MASTERCARD]"},
    {"DF1E", "Counter 2 Control (Contactless) [MASTERCARD]"},
    {"DF1F", "Counter 2 Lower Limit [MASTERCARD]"},
    {"DF21", "Transaction Profile Objects 1 [DISCOVER] OR Counter 2 Upper Limit [MASTERCARD] OR Transaction Profile Objects 1 [TROY] OR Contactless Transaction Counter Lower Limit in BF55 (CLTCLL) [VISA] OR Consecutive Transaction Counter Limit in BF56 (CTCL) [VISA] OR Consecutive Transaction Counter International Limit in BF57 (CTCIL) [VISA] OR Cumulative Total Transaction Amount Limit (CTTAL) in BF58 [VISA]"},
    {"DF4D", "NA"},
    {"DF49", "NA"},
    {"DF4A", "NA"},
    {"9F6E", "Third Party Data  [MASTERCARD] OR Form Factor Indicator (FFI) [VISA]"},
    {"9F5D", "Available Offline Spending Amount OR Application Capabilities Information [MASTERCARD]"},
    {"DF60", "NA"},
    {"DF61", "VLP Reset Threshold in BF55 [VISA] OR Consecutive Transaction Counter International Country Limit in BF57 (CTCICL) [VISA]"},
    {"DF48", "NA"},
    {"DF56", "NA"},
    {"DF5F", "NA"},
    {"DF4C", "NA"},
    {"DF50", "NA"},
    {"DF53", "NA"},
    {"DF57", "NA"},
    {"DF58", "NA"},
    {"9F2A", "NA"},
    {"DF43", "CL-Counter [DISCOVER] OR CL-Counter [TROY]"},
    {"DF44", "CL-Cons Limit [DISCOVER] OR CL-Cons Limit [TROY]"},
    {"9F51", "DRDOL [MASTERCARD] OR Application Currency Code [VISA]"}

    };
  }
}
